[package]
name = "mailscope-connector-imap"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
async-imap = "0.9"
futures = "0.3"
async-native-tls = "0.5"
tokio-util = { workspace = true }
mailparse = "0.14"
mailscope-core = { path = "../../core" }
